//---------------------------------------------------------------------------

#ifndef MainFormKSH
#define MainFormKSH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include <IniFiles.hpp>
#include <Chart.hpp>
#include <Grids.hpp>
#include <Series.hpp>
#include <TeEngine.hpp>
#include <TeeProcs.hpp>
#include <ADODB.hpp>
#include <Db.hpp>
#include <CheckLst.hpp>
#include "CGAUGES.h"
#include "DBGridEh.hpp"
#include "ClassArhiv.hpp"
#include <Dialogs.hpp>
#define NumPageArhivSob 5    // номер страницы с архивом событий (от 0)
#define NumPageTrends   6    // номер страницы с трендами (от 0)
#define CountForTrends  1000 // количество тэгов для построения трендов
//---------------------------------------------------------------------------
MyArhiv *ActiveArhiv;
class TFMainForm : public TForm
{
__published:	// IDE-managed Components
        TPageControl *PageControl1;
        TTabSheet *TabSheet1;
        TImage *Image1;
        TShape *Shape1;
        TShape *Shape2;
        TShape *Shape311;
        TShape *Shape3;
        TPanel *Panel1;
        TPanel *PListArhiv;
        TTrackBar *TrackBar1;
        TPanel *Panel69;
        TStaticText *StaticText60;
        TDateTimePicker *DTPTimeBegin;
        TDateTimePicker *DTPDateBegin;
        TStaticText *StaticText61;
        TDateTimePicker *DTPTimeEnd;
        TDateTimePicker *DTPDateEnd;
        TBitBtn *BitBtn3;
        TBitBtn *BitBtn4;
        TPanel *Panel70;
        TSpeedButton *SpeedButton2;
        TBitBtn *BitBtn2;
        TTimer *Timer1;
        TTabSheet *TabSheet2;
        TTabSheet *TabSheet3;
        TPanel *P1;
        TSplitter *Splitter5;
        TPanel *Panel72;
        TStaticText *StaticText134;
        TListBox *LBListTrends;
        TPanel *Panel73;
        TSplitter *Splitter6;
        TPanel *Panel74;
        TBitBtn *BitBtn6;
        TBitBtn *BitBtn7;
        TStaticText *StaticText136;
        TDBGridEh *DBGridEh4;
        TPanel *Panel75;
        TPanel *Panel76;
        TBitBtn *BitBtn8;
        TBitBtn *BitBtn9;
        TStaticText *StaticText142;
        TDBGridEh *DBGridEh5;
        TSplitter *Splitter3;
        TPanel *PanelTrend;
        TSplitter *Splitter4;
        TPanel *Panel71;
        TSpeedButton *SBPlus;
        TSpeedButton *SBMinus;
        TSpeedButton *SpeedButton3;
        TSpeedButton *SBTagMinus;
        TSpeedButton *SBHourMinus;
        TSpeedButton *SBHourPlus;
        TSpeedButton *SBTagPlus;
        TStaticText *StaticText90;
        TDateTimePicker *DTPTime_beginTrend;
        TDateTimePicker *DTPDate_beginTrend;
        TStaticText *StaticText118;
        TDateTimePicker *DTPTime_endTrend;
        TDateTimePicker *DTPDate_endTrend;
        TBitBtn *BBBuilderTrend;
        TStaticText *STTimeTrend;
        TPanel *PView;
        TDBGridEh *DBGridEh6;
        TTrackBar *TBValue;
        TChart *Trends;
        TLineSeries *Series1;
        TTimer *Timer2;
        TDataSource *DSListTags;
        TADOQuery *QListTags;
        TIntegerField *QListTagsIDTag;
        TWideStringField *QListTagsNameTag;
        TWideStringField *QListTagsCaptionTag;
        TFloatField *QListTagsValueTag;
        TIntegerField *QListTagsStatusTag;
        TWideStringField *QListTagsTypeOpros;
        TWideStringField *QListTagsParam1;
        TWideStringField *QListTagsParam2;
        TWideStringField *QListTagsParam3;
        TIntegerField *QListTagsTypeValue;
        TIntegerField *QListTagsNumEkran;
        TIntegerField *QListTagsTypeVisibleElement;
        TWideStringField *QListTagsVisParam1;
        TWideStringField *QListTagsVisParam2;
        TFloatField *QListTagsMinVal;
        TFloatField *QListTagsMaxVal;
        TFloatField *QListTagsMinValIn;
        TFloatField *QListTagsMaxValIn;
        TIntegerField *QListTagsVisParam3;
        TIntegerField *QListTagsVisParam4;
        TIntegerField *QListTagsTypeVisibleArhiv;
        TIntegerField *QListTagsTypeArhiv;
        TIntegerField *QListTagsUslAvar;
        TADOConnection *ConArhiv;
        TDataSource *DSFiltr;
        TADOQuery *QFiltr;
        TIntegerField *QFiltrIDRec;
        TIntegerField *QFiltrIDTag;
        TBooleanField *QFiltrActive;
        TIntegerField *QFiltrTypeFiltr;
        TIntegerField *QFiltrIndexInList;
        TADOConnection *ConFiltr;
        TPanel *Panel64;
        TStaticText *StaticText53;
        TDBGridEh *DBGridEh2;
        TPanel *Panel68;
        TButton *Button4;
        TSplitter *Splitter1;
        TPanel *Panel65;
        TSplitter *Splitter2;
        TStaticText *StaticText56;
        TPanel *Panel66;
        TSpeedButton *SpeedButton1;
        TStaticText *StaticText57;
        TDateTimePicker *DTPTime_begin;
        TDateTimePicker *DTPDate_begin;
        TStaticText *StaticText58;
        TDateTimePicker *DTPTime_end;
        TDateTimePicker *DTPDate_end;
        TBitBtn *BitBtn12;
        TBitBtn *BitBtn1;
        TBitBtn *BBLastHour;
        TPanel *Panel67;
        TStaticText *StaticText59;
        TCheckListBox *CLBFS;
        TDBGridEh *DBGridEh3;
        TDataSource *DSActiveSob;
        TADOQuery *QActiveSob;
        TIntegerField *QActiveSobIDSob;
        TDateTimeField *QActiveSobDTSob;
        TIntegerField *QActiveSobIDTag;
        TIntegerField *QActiveSobVal;
        TBooleanField *QActiveSobActive;
        TBooleanField *QActiveSobKvitirov;
        TADOConnection *ConActiveSob;
        TDataSource *DSListSob;
        TADOQuery *QListSob;
        TIntegerField *QListSobIDSob;
        TDateTimeField *QListSobDTSob;
        TIntegerField *QListSobIDTag;
        TIntegerField *QListSobVal;
        TBooleanField *QListSobActive;
        TBooleanField *QListSobActive1;
        TDateTimeField *QListSobDlit;
        TADOConnection *ConListSob;
        TDataSource *DSViewData;
        TADOQuery *QViewData;
        TIntegerField *QViewDataIDInfo;
        TIntegerField *QViewDataIDTrend;
        TIntegerField *QViewDataIDTag;
        TIntegerField *QViewDataColorLine;
        TDateTimeField *QViewDataTDT;
        TFloatField *QViewDataVal;
        TIntegerField *QViewDataStatus;
        TFloatField *QViewDataValProc;
        TBooleanField *QViewDataActive;
        TADOConnection *ConViewData;
        TDataSource *DSConChecktrend;
        TADOQuery *QConCheckTrend;
        TIntegerField *QConCheckTrendIDInfo;
        TIntegerField *QConCheckTrendIDTrend;
        TIntegerField *QConCheckTrendIDTag;
        TIntegerField *QConCheckTrendColorLine;
        TDateTimeField *QConCheckTrendTDT;
        TFloatField *QConCheckTrendVal;
        TIntegerField *QConCheckTrendStatus;
        TFloatField *QConCheckTrendValProc;
        TADOConnection *ConCheckTrend;
        TDataSource *DSListTrend;
        TADOQuery *QListTrend;
        TIntegerField *QListTrendIDTrend;
        TWideStringField *QListTrendCaptionTrend;
        TADOConnection *ConListTrend;
        TPanel *Vizir;
        TShape *Shape4;
        TShape *Shape8;
        TShape *Shape9;
        TShape *Shape13;
        TImage *Image2;
        TShape *Shape12;
        TShape *Shape14;
        TShape *Shape15;
        TShape *Shape16;
        TShape *Shape17;
        TShape *Shape18;
        TShape *Shape19;
        TImage *DI_FIRE_E1;
        TShape *Shape20;
        TLabel *Label10;
        TShape *Shape22;
        TLabel *Label11;
        TDataSource *DSListPos;
        TADOQuery *QListPos;
        TWideStringField *QListPosNameTag;
        TWideStringField *QListPosCaptionTag;
        TIntegerField *QListPosIDTag;
        TADOConnection *ConListPos;
        TColorDialog *ColorDialog1;
        TDataSource *DSTmp;
        TADOQuery *QTmp;
        TADOConnection *ConTmp;
        TLabel *EI_01_E1;
        TLabel *ER_01_E1;
        TShape *DI_24_E1;
        TLabel *DI_12_E1;
        TLabel *DI_13_E1;
        TLabel *L1_E1;
        TLabel *L2_E1;
        TLabel *L3_E1;
        TLabel *L4_E1;
        TLabel *L5_E1;
        TLabel *L6_E1;
        TLabel *L7_E1;
        TLabel *L8_E1;
        TLabel *L9_E1;
        TLabel *L10_E1;
        TLabel *L11_E1;
        TLabel *L12_E1;
        TLabel *L13_E1;
        TLabel *L14_E1;
        TLabel *L15_E1;
        TLabel *L16_E1;
        TLabel *DI_10_E1;
        TTabSheet *TabSheet4;
        TShape *Shape54;
        TShape *Shape55;
        TShape *Shape56;
        TShape *Shape57;
        TImage *Image4;
        TLabel *Label36;
        TLabel *Label43;
        TShape *Shape113;
        TShape *Shape114;
        TLabel *Label44;
        TShape *Shape115;
        TLabel *PC_206_E2;
        TShape *Shape116;
        TShape *Shape117;
        TShape *Shape118;
        TImage *PV741_C_E2;
        TShape *Shape119;
        TShape *Shape120;
        TLabel *LC_403_E2;
        TLabel *TLT_403_E2;
        TCGauge *LC_403L_E2;
        TShape *Shape121;
        TShape *Shape122;
        TImage *PV721_C_E2;
        TShape *Shape123;
        TImage *Image35;
        TLabel *Label78;
        TCGauge *LI_401L_E2;
        TLabel *TLT_401_E2;
        TShape *Shape209;
        TShape *Shape208;
        TLabel *LI_401_E2;
        TImage *Image36;
        TLabel *Label81;
        TCGauge *LI_402L_E2;
        TLabel *TLT_402_E2;
        TShape *Shape210;
        TShape *Shape212;
        TLabel *LI_402_E2;
        TShape *Shape216;
        TShape *Shape217;
        TShape *Shape218;
        TShape *Shape219;
        TLabel *Label84;
        TShape *Shape220;
        TShape *Shape221;
        TLabel *TI_105_E2;
        TShape *Shape187;
        TShape *Shape223;
        TShape *Shape224;
        TLabel *Label2;
        TShape *Shape7;
        TShape *Shape23;
        TLabel *Label5;
        TShape *Shape24;
        TImage *Image3;
        TShape *Npod_E2;
        TShape *Shape26;
        TShape *Shape27;
        TImage *Image31;
        TImage *Image32;
        TImage *Image33;
        TShape *N1gvs_E2;
        TShape *N2gvs_E2;
        TShape *N3gvs_E2;
        TShape *Shape192;
        TLabel *Label72;
        TShape *Shape193;
        TShape *Shape194;
        TShape *Shape195;
        TShape *Shape196;
        TShape *Shape197;
        TShape *Shape198;
        TShape *Shape199;
        TShape *Shape200;
        TImage *Image34;
        TShape *N4gvs_E2;
        TShape *Shape201;
        TShape *Shape202;
        TShape *Shape213;
        TShape *Shape28;
        TShape *Shape29;
        TLabel *Label7;
        TShape *Shape30;
        TLabel *Label12;
        TImage *Image23;
        TImage *Image24;
        TImage *Image25;
        TShape *N1set_E2;
        TShape *N2set_E2;
        TShape *N3set_E2;
        TShape *Shape129;
        TShape *Shape130;
        TLabel *Label51;
        TShape *Shape131;
        TShape *Shape132;
        TShape *Shape133;
        TShape *Shape134;
        TShape *Shape135;
        TShape *Shape136;
        TShape *Shape137;
        TLabel *Label58;
        TShape *Shape161;
        TShape *Shape162;
        TLabel *TI_101_E2;
        TLabel *Label60;
        TShape *Shape163;
        TShape *Shape164;
        TLabel *TI_102_E2;
        TLabel *Label62;
        TShape *Shape165;
        TShape *Shape166;
        TLabel *TI_103_E2;
        TShape *Shape168;
        TShape *Shape169;
        TLabel *Label64;
        TLabel *TPT_204_E2;
        TShape *Shape179;
        TShape *Shape180;
        TLabel *PC_204_E2;
        TShape *Shape178;
        TShape *Shape181;
        TShape *Shape182;
        TShape *Shape183;
        TLabel *Label67;
        TShape *Shape185;
        TImage *PV711_C_E2;
        TShape *Shape230;
        TImage *Z3_C_E2;
        TLabel *Label97;
        TShape *Shape167;
        TImage *Image11;
        TImage *Image12;
        TImage *Image13;
        TShape *N1pit_E2;
        TShape *N2pit_E2;
        TShape *N3pit_E2;
        TShape *Shape50;
        TLabel *Label15;
        TShape *Shape51;
        TShape *Shape52;
        TShape *Shape53;
        TShape *Shape58;
        TShape *Shape59;
        TShape *Shape60;
        TShape *Shape61;
        TLabel *TPT_201_E2;
        TShape *Shape70;
        TShape *Shape71;
        TLabel *PT_201_E2;
        TLabel *TPT_202_E2;
        TShape *Shape72;
        TShape *Shape73;
        TLabel *PT_202_E2;
        TShape *Shape67;
        TShape *Shape69;
        TImage *Image27;
        TImage *Image28;
        TShape *N1pod_E2;
        TShape *N2pod_E2;
        TShape *Shape174;
        TShape *Shape175;
        TShape *Shape176;
        TShape *Shape31;
        TShape *Shape186;
        TShape *Shape215;
        TShape *Shape146;
        TShape *Shape147;
        TShape *Shape148;
        TShape *Shape149;
        TShape *Shape150;
        TShape *Shape151;
        TShape *Shape152;
        TShape *Shape153;
        TShape *Shape154;
        TShape *Shape155;
        TShape *Shape156;
        TShape *Shape139;
        TLabel *Label13;
        TShape *Shape80;
        TImage *Image16;
        TImage *Image17;
        TImage *Image18;
        TShape *Shape85;
        TShape *Shape86;
        TShape *Shape87;
        TShape *Shape88;
        TShape *Shape89;
        TShape *Shape91;
        TLabel *Label30;
        TShape *Shape93;
        TShape *Shape94;
        TLabel *PC_212_E2;
        TLabel *Label32;
        TShape *Shape95;
        TShape *Shape96;
        TLabel *PC_213_E2;
        TShape *Shape97;
        TShape *Shape98;
        TShape *Shape99;
        TShape *Shape100;
        TShape *Shape101;
        TImage *PV761_C_E2;
        TImage *PV771_C_E2;
        TLabel *Label34;
        TLabel *Label35;
        TShape *Shape102;
        TShape *Shape103;
        TShape *Shape104;
        TShape *Shape105;
        TLabel *TPT_211_E2;
        TShape *Shape106;
        TShape *Shape107;
        TLabel *PT_211_E2;
        TShape *Shape110;
        TShape *Shape111;
        TShape *Shape112;
        TShape *Shape138;
        TShape *Shape141;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *TPT_203_E2;
        TShape *Shape158;
        TShape *Shape159;
        TLabel *PT_203_E2;
        TLabel *Label56;
        TShape *Shape145;
        TShape *Shape160;
        TLabel *TI_104_E2;
        TLabel *Label55;
        TShape *Shape157;
        TShape *Shape74;
        TShape *Shape32;
        TImage *Image6;
        TShape *Shape36;
        TLabel *Label14;
        TShape *Shape62;
        TLabel *Label71;
        TShape *Shape211;
        TShape *Shape90;
        TLabel *TI_106_E2;
        TCGauge *LC_404L_E2;
        TLabel *TLT_404_E2;
        TShape *Shape65;
        TShape *Shape66;
        TLabel *LC_404_E2;
        TLabel *Label23;
        TShape *Shape68;
        TShape *Shape75;
        TShape *Shape76;
        TImage *PV731_C_E2;
        TShape *Shape77;
        TShape *Shape78;
        TShape *Shape79;
        TImage *PV751_C_E2;
        TShape *Shape81;
        TShape *Shape83;
        TShape *Shape84;
        TLabel *Label37;
        TLabel *Label47;
        TShape *Shape92;
        TShape *Shape33;
        TLabel *Label42;
        TShape *Shape34;
        TShape *Shape140;
        TShape *Shape144;
        TImage *Image29;
        TImage *Image26;
        TLabel *Label50;
        TImage *Image7;
        TImage *Image10;
        TShape *N10con_E2;
        TShape *Shape37;
        TShape *Shape38;
        TShape *Shape39;
        TLabel *Label16;
        TLabel *LS411_Max_E2;
        TLabel *LS411_Mid_E2;
        TLabel *LS411_Min_E2;
        TCGauge *LS411_E2;
        TShape *Shape40;
        TStaticText *StaticText20;
        TStaticText *StaticText22;
        TStaticText *StaticText11;
        TStaticText *StaticText2;
        TStaticText *N1gvs_av_E2;
        TStaticText *N3gvs_av_E2;
        TStaticText *N4gvs_av_E2;
        TStaticText *StaticText4;
        TStaticText *StaticText5;
        TStaticText *StaticText7;
        TStaticText *StaticText6;
        TStaticText *StaticText17;
        TStaticText *StaticText18;
        TStaticText *StaticText19;
        TStaticText *StaticText23;
        TStaticText *StaticText8;
        TStaticText *StaticText9;
        TStaticText *StaticText10;
        TStaticText *StaticText14;
        TStaticText *StaticText16;
        TStaticText *Time_E2;
        TStaticText *StaticText26;
        TStaticText *StaticText13;
        TStaticText *StaticText21;
        TStaticText *StaticText24;
        TStaticText *StaticText28;
        TStaticText *StaticText12;
        TStaticText *StaticText29;
        TStaticText *StaticText30;
        TStaticText *StaticText31;
        TStaticText *StaticText32;
        TLabel *Label17;
        TShape *Shape41;
        TShape *Shape42;
        TShape *Shape43;
        TShape *Shape44;
        TShape *Shape45;
        TShape *Shape46;
        TShape *Shape47;
        TShape *Shape48;
        TStaticText *StaticText15;
        TShape *Shape49;
        TShape *Shape63;
        TLabel *Label90;
        TShape *Shape225;
        TImage *Image8;
        TImage *Image9;
        TImage *Image14;
        TShape *N1pov_E2;
        TShape *N2pov_E2;
        TShape *N3pov_E2;
        TShape *Shape64;
        TShape *Shape82;
        TShape *Shape124;
        TShape *Shape125;
        TLabel *Label18;
        TShape *Shape126;
        TShape *Shape127;
        TShape *Shape128;
        TShape *Shape142;
        TShape *Shape143;
        TShape *Shape170;
        TShape *Shape171;
        TShape *Shape172;
        TLabel *Label19;
        TImage *Image37;
        TLabel *Label86;
        TLabel *TLT_412_E2;
        TCGauge *LS412_E2;
        TImage *Image38;
        TLabel *Label88;
        TLabel *TLT_413_E2;
        TCGauge *LS413_E2;
        TImage *Image39;
        TImage *Image40;
        TShape *N11dre_E2;
        TShape *Shape227;
        TShape *Shape228;
        TShape *Shape229;
        TLabel *Label92;
        TLabel *LS408_Max_E2;
        TLabel *LS408_Min_E2;
        TCGauge *LS408_E2;
        TLabel *Label96;
        TStaticText *StaticText27;
        TStaticText *StaticText33;
        TStaticText *PS208_E2;
        TStaticText *PS209_E2;
        TLabel *Label20;
        TLabel *TPS_209_E2;
        TLabel *Label24;
        TLabel *TPS_208_E2;
        TLabel *TPT_205_E2;
        TShape *Shape203;
        TShape *Shape204;
        TLabel *PT_205_E2;
        TLabel *Label75;
        TShape *Shape205;
        TShape *Shape206;
        TLabel *TI_107_E2;
        TLabel *Label28;
        TShape *Shape177;
        TLabel *PI_01_E1;
        TShape *Shape184;
        TLabel *Label29;
        TShape *Shape188;
        TLabel *PE_01_E1;
        TStaticText *StaticText34;
        TLabel *Label33;
        TStaticText *Time_E1;
        TStaticText *StaticText40;
        TImage *Image5;
        TImage *DI_32_E1;
        TShape *Shape21;
        TLabel *Label4;
        TShape *Shape189;
        TLabel *PZ_01_E1;
        TImage *DI_31_E1;
        TStaticText *StaticText1;
        TLabel *Label6;
        TShape *Shape10;
        TLabel *Label8;
        TShape *Shape11;
        TLabel *PZ_02_E1;
        TStaticText *StaticText3;
        TLabel *Label1;
        TImage *Image15;
        TShape *Shape5;
        TLabel *Label3;
        TImage *Image19;
        TShape *Shape6;
        TLabel *Label9;
        TShape *Shape190;
        TLabel *Label31;
        TShape *Shape191;
        TLabel *AI_01_E1;
        TShape *Shape207;
        TStaticText *N2Gvs_Rez_E2;
        TStaticText *N3Gvs_Rez_E2;
        TStaticText *N4Gvs_Rez_E2;
        TStaticText *N1Set_Rez_E2;
        TStaticText *N2Set_Rez_E2;
        TStaticText *N3Set_Rez_E2;
        TStaticText *N1Pit_Rez_E2;
        TStaticText *N2Pit_Rez_E2;
        TStaticText *N3Pit_Rez_E2;
        TShape *Shape214;
        TLabel *Mode_DreN11_E2;
        TShape *Shape222;
        TLabel *Mode_ConN10_E2;
        TButton *Button1;
        TButton *Button2;
        TButton *Button3;
        TStaticText *Zad3_Avar_E2;
        TShape *Shape35;
        TLabel *R1_PC204_Mode_E2;
        TShape *Shape226;
        TLabel *R2_PC206_Mode_E2;
        TShape *Shape231;
        TLabel *R3_PC207_Mode_E2;
        TShape *Shape232;
        TLabel *R4_PC212_Mode_E2;
        TShape *Shape233;
        TLabel *R5_PC213_Mode_E2;
        TShape *Shape234;
        TLabel *R6_LC403_Mode_E2;
        TShape *Shape235;
        TLabel *R7_LC404_Mode_E2;
        TButton *Button5;
        TBitBtn *BitBtn5;
        TStaticText *LV721_Op_E2;
        TStaticText *LV721_Cl_E2;
        TStaticText *PV751_Op_E2;
        TStaticText *PV751_Cl_E2;
        TStaticText *LV731_Op_E2;
        TStaticText *LV731_Cl_E2;
        TStaticText *PV741_Op_E2;
        TStaticText *PV741_Cl_E2;
        TStaticText *PV761_Op_E2;
        TStaticText *PV761_Cl_E2;
        TStaticText *PV771_Op_E2;
        TStaticText *PV771_Cl_E2;
        TStaticText *PV711_Op_E2;
        TStaticText *PV711_Cl_E2;
        TStaticText *TNO_E2;
        TStaticText *TOB1_E2;
        TStaticText *TOB2_E2;
        TStaticText *TOB3_E2;
        TTabSheet *TabSheet5;
        TImage *Image20;
        TShape *ShapeBurner;
        TImage *K1Fire_E3;
        TShape *GasPipe4;
        TShape *igniter1;
        TShape *GasPipe5;
        TShape *igniter3;
        TShape *igniter2;
        TShape *GasPipe3;
        TShape *GasPipeOut1;
        TShape *GasPipe2;
        TImage *K1Klap1_E3;
        TShape *SDI24;
        TShape *SDI23;
        TShape *Shape241;
        TShape *Shape242;
        TImage *K1KlapZap_E3;
        TShape *Shape236;
        TShape *Shape237;
        TImage *K1KlapSweb_E3;
        TShape *Shape238;
        TLabel *Label21;
        TStaticText *StaticText25;
        TStaticText *StaticText35;
        TLabel *Label38;
        TShape *Shape243;
        TShape *Shape244;
        TLabel *K1PI_01_E3;
        TImage *K1Klap2_E3;
        TLabel *Label40;
        TShape *Shape245;
        TShape *Shape246;
        TLabel *K1S_02_E3;
        TImage *IDI06;
        TShape *Air;
        TLabel *Label45;
        TStaticText *StaticText36;
        TLabel *Label48;
        TShape *Shape247;
        TShape *Shape248;
        TLabel *K1CRPVoz_Q_E3;
        TShape *Shape249;
        TLabel *K1ModeVoz_E3;
        TImage *ImageFanAir;
        TShape *SDI_voz_E3;
        TShape *SteamPipe1;
        TShape *SteamPipe2;
        TLabel *Label61;
        TShape *Shape252;
        TShape *Shape253;
        TLabel *K1PC_04_E3;
        TLabel *Label65;
        TStaticText *StaticText37;
        TImage *ImageEconomizer;
        TShape *WaterPipeInside1;
        TShape *WaterPipeInside2;
        TShape *FlueGas1;
        TImage *ImageFanFlueGas;
        TShape *SDI_dym_E3;
        TLabel *Label66;
        TStaticText *StaticText38;
        TStaticText *StaticText39;
        TLabel *Label73;
        TShape *Shape256;
        TLabel *K1ModeDym_E3;
        TShape *Shape254;
        TLabel *Label74;
        TShape *Shape255;
        TLabel *K1CRPDym_Q_E3;
        TLabel *Label79;
        TShape *Shape257;
        TShape *Shape258;
        TLabel *K1TI_02_E3;
        TShape *ShapeFlueGasOut;
        TLabel *Label82;
        TShape *Shape259;
        TShape *Shape260;
        TLabel *K1TI_01_E3;
        TShape *FlueGas2;
        TShape *Shape261;
        TShape *Shape262;
        TLabel *K1ModeGaz_E3;
        TShape *Shape263;
        TLabel *K1ModeVod_E3;
        TLabel *Label89;
        TShape *Shape264;
        TLabel *K1Q_vody_E3;
        TLabel *Label93;
        TShape *Shape265;
        TShape *Shape266;
        TLabel *K1S_01_E3;
        TLabel *Label95;
        TShape *Shape267;
        TShape *Shape268;
        TLabel *K1TI_04_E3;
        TShape *WaterPipeIn;
        TImage *Image22;
        TLabel *Label99;
        TShape *Shape269;
        TShape *Shape270;
        TLabel *K1TI_03_E3;
        TShape *WaterPipeInside3;
        TShape *Shape271;
        TLabel *Label101;
        TLabel *K3SIg1_E3;
        TLabel *K3SIg2_E3;
        TLabel *K3SIg3_E3;
        TLabel *K3SIg4_E3;
        TLabel *K3SIg5_E3;
        TLabel *K3SIg6_E3;
        TLabel *K3SIg7_E3;
        TLabel *K3SIg8_E3;
        TLabel *K3SIg9_E3;
        TLabel *K3SIg10_E3;
        TLabel *K3SIg11_E3;
        TLabel *K3SIg13_E3;
        TLabel *K3SIg14_E3;
        TShape *Shape272;
        TLabel *Label116;
        TLabel *K3Sost_gotov_E3;
        TLabel *K3Sost_vent_E3;
        TLabel *K3Sost_opress_E3;
        TLabel *K3Sost_gotovr_E3;
        TLabel *K3Sost_rozg_E3;
        TLabel *K3Sost_prog_E3;
        TLabel *K3Sost_avar_E3;
        TLabel *K3Sost_work_E3;
        TStaticText *Time_E3;
        TStaticText *StaticText42;
        TLabel *K3Sost_sign_E3;
        TShape *Shape273;
        TLabel *Label125;
        TLabel *K3Av01_E3;
        TLabel *K3Av02_E3;
        TLabel *K3Av03_E3;
        TLabel *K3Av04_E3;
        TLabel *K3Av05_E3;
        TLabel *K3Av06_E3;
        TLabel *K3Av07_E3;
        TLabel *K3Av08_E3;
        TLabel *K3Av09_E3;
        TLabel *K3Av10_E3;
        TLabel *K3Av11_E3;
        TLabel *K3Av12_E3;
        TLabel *K3Av13_E3;
        TLabel *K3Av14_E3;
        TLabel *K3Av15_E3;
        TLabel *K3Av16_E3;
        TLabel *K3Av17_E3;
        TLabel *K3Av18_E3;
        TLabel *K3Av19_E3;
        TLabel *K3Av20_E3;
        TLabel *K3Av21_E3;
        TLabel *K3Av22_E3;
        TLabel *K3SIg12_E3;
        TShape *Shape274;
        TShape *Shape275;
        TLabel *K1LI_02_E3;
        TCGauge *K1LI_02L_E3;
        TLabel *Label150;
        TShape *Shape276;
        TShape *Shape277;
        TLabel *K1LI_01_E3;
        TCGauge *K1LI_01L_E3;
        TLabel *Label152;
        TLabel *Label39;
        TShape *Shape278;
        TShape *Shape279;
        TLabel *K1PC_02_E3;
        TLabel *PDC_E3;
        TShape *Shape280;
        TLabel *K1PI_03_E3;
        TLabel *PC_207_E2;
        TShape *Shape108;
        TLabel *Label46;
        TShape *Shape109;
        TLabel *Label22;
        TLabel *Label25;
        TLabel *Label26;
        TLabel *Label27;
        TLabel *Label41;
        TLabel *Label49;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label57;
        TLabel *Label59;
        TLabel *Label63;
        TLabel *Label76;
        TLabel *Label77;
        TLabel *Label80;
        TLabel *Label83;
        TLabel *Label85;
        TShape *Shape239;
        TShape *Shape173;
        TLabel *TI_108_E2;
        TShape *Shape240;
        TImage *Image21;
        TLabel *Label87;
        TCGauge *LS407_E2;
        TLabel *LS408_Mid_E2;
        TBitBtn *BitBtn10;
        TShape *Shape250;
        TLabel *Label91;
        TLabel *Label94;
        TLabel *Label98;
        TShape *Shape251;
        TShape *Shape281;
        TShape *Shape282;
        TLabel *Label100;
        TLabel *Label102;
        TShape *Shape283;
        TShape *Shape284;
        TShape *Shape285;
        TLabel *K1Q_oh_E3;
        TShape *Shape286;
        TLabel *K1Q_th_E3;
        TShape *Shape287;
        TLabel *K1Q_od_E3;
        TShape *Shape288;
        TLabel *K1Q_td_E3;
        TTabSheet *TabSheet6;
        TImage *Image30;
        TShape *Shape289;
        TImage *DE2_K1Fire_E4;
        TShape *Shape290;
        TShape *Shape291;
        TShape *Shape292;
        TShape *Shape293;
        TShape *Shape294;
        TShape *Shape295;
        TShape *Shape296;
        TShape *Shape297;
        TImage *DE2_K1Klap1_E4;
        TShape *Shape298;
        TShape *Shape299;
        TShape *Shape300;
        TShape *Shape301;
        TImage *DE2_K1KlapZap_E4;
        TShape *Shape302;
        TShape *Shape303;
        TImage *DE2_K1KlapSweb_E4;
        TShape *Shape304;
        TLabel *Label103;
        TLabel *Label104;
        TShape *Shape305;
        TShape *Shape306;
        TLabel *DE2_K1PI_01_E4;
        TImage *DE2_K1Klap2_E4;
        TLabel *Label106;
        TShape *Shape307;
        TShape *Shape308;
        TLabel *DE2_K1S_02_E4;
        TImage *Image46;
        TShape *Shape309;
        TLabel *Label108;
        TLabel *Label109;
        TShape *Shape310;
        TShape *Shape312;
        TLabel *DE2_K1CRPVoz_Q_E4;
        TShape *Shape313;
        TLabel *DE2_K1ModeVoz_E4;
        TImage *Image47;
        TShape *DE2_SDI_voz_E4;
        TShape *Shape315;
        TShape *Shape316;
        TLabel *Label112;
        TShape *Shape317;
        TShape *Shape318;
        TLabel *DE2_K1PC_04_E4;
        TLabel *Label114;
        TImage *Image48;
        TShape *Shape319;
        TShape *Shape320;
        TShape *Shape321;
        TImage *Image49;
        TShape *DE2_SDI_dym_E4;
        TLabel *Label115;
        TLabel *Label117;
        TShape *Shape323;
        TLabel *DE2_K1ModeDym_E4;
        TShape *Shape324;
        TLabel *Label119;
        TShape *Shape325;
        TLabel *DE2_K1CRPDym_Q_E4;
        TLabel *Label121;
        TShape *Shape326;
        TShape *Shape327;
        TLabel *DE2_K1TI_02_E4;
        TShape *Shape328;
        TLabel *Label123;
        TShape *Shape329;
        TShape *Shape330;
        TLabel *DE2_K1TI_01_E4;
        TShape *Shape331;
        TShape *Shape332;
        TShape *Shape333;
        TLabel *DE2_K1ModeGaz_E4;
        TShape *Shape334;
        TLabel *DE2_K1ModeVod_E4;
        TLabel *Label128;
        TShape *Shape335;
        TLabel *DE2_K1Q_vody_E4;
        TLabel *Label130;
        TShape *Shape336;
        TShape *Shape337;
        TLabel *DE2_K1S_01_E4;
        TLabel *Label132;
        TShape *Shape338;
        TShape *Shape339;
        TLabel *DE2_K1TI_04_E4;
        TShape *Shape340;
        TImage *Image50;
        TLabel *Label134;
        TShape *Shape341;
        TShape *Shape342;
        TLabel *DE2_K1TI_03_E4;
        TShape *Shape343;
        TShape *Shape344;
        TLabel *Label136;
        TLabel *DE2_K3SIg1_E4;
        TLabel *DE2_K3SIg2_E4;
        TLabel *DE2_K3SIg3_E4;
        TLabel *DE2_K3SIg4_E4;
        TLabel *DE2_K3SIg5_E4;
        TLabel *DE2_K3SIg6_E4;
        TLabel *DE2_K3SIg7_E4;
        TLabel *DE2_K3SIg8_E4;
        TLabel *DE2_K3SIg9_E4;
        TLabel *DE2_K3SIg10_E4;
        TLabel *DE2_K3SIg11_E4;
        TLabel *DE2_K3SIg13_E4;
        TLabel *DE2_K3SIg14_E4;
        TShape *Shape345;
        TLabel *Label151;
        TLabel *DE2_K3Sost_gotov_E4;
        TLabel *DE2_K3Sost_vent_E4;
        TLabel *DE2_K3Sost_opress_E4;
        TLabel *DE2_K3Sost_gotovr_E4;
        TLabel *DE2_K3Sost_rozg_E4;
        TLabel *DE2_K3Sost_prog_E4;
        TLabel *DE2_K3Sost_avar_E4;
        TLabel *DE2_K3Sost_work_E4;
        TLabel *DE2_K3Sost_sign_E4;
        TShape *Shape346;
        TLabel *Label162;
        TLabel *DE2_K3Av01_E4;
        TLabel *DE2_K3Av02_E4;
        TLabel *DE2_K3Av03_E4;
        TLabel *DE2_K3Av04_E4;
        TLabel *DE2_K3Av05_E4;
        TLabel *DE2_K3Av06_E4;
        TLabel *DE2_K3Av07_E4;
        TLabel *DE2_K3Av08_E4;
        TLabel *DE2_K3Av09_E4;
        TLabel *DE2_K3Av10_E4;
        TLabel *DE2_K3Av11_E4;
        TLabel *DE2_K3Av12_E4;
        TLabel *DE2_K3Av13_E4;
        TLabel *DE2_K3Av14_E4;
        TLabel *DE2_K3Av15_E4;
        TLabel *DE2_K3Av16_E4;
        TLabel *DE2_K3Av17_E4;
        TLabel *DE2_K3Av18_E4;
        TLabel *DE2_K3Av19_E4;
        TLabel *DE2_K3Av20_E4;
        TLabel *DE2_K3Av21_E4;
        TLabel *DE2_K3Av22_E4;
        TLabel *DE2_K3SIg12_E4;
        TShape *Shape347;
        TShape *Shape348;
        TLabel *DE2_K1LI_02_E4;
        TCGauge *DE2_K1LI_02L_E4;
        TLabel *Label187;
        TShape *Shape349;
        TShape *Shape350;
        TLabel *DE2_K1LI_01_E4;
        TCGauge *DE2_K1LI_01L_E4;
        TLabel *Label189;
        TLabel *Label190;
        TShape *Shape351;
        TShape *Shape352;
        TLabel *DE2_K1PC_02_E4;
        TLabel *Label192;
        TShape *Shape353;
        TLabel *DE2_K1PI_03_E4;
        TShape *Shape354;
        TLabel *Label194;
        TLabel *Label195;
        TLabel *Label196;
        TShape *Shape355;
        TShape *Shape356;
        TShape *Shape357;
        TLabel *Label197;
        TLabel *Label198;
        TShape *Shape358;
        TShape *Shape359;
        TShape *Shape360;
        TLabel *DE2_K1Q_oh_E4;
        TShape *Shape361;
        TLabel *DE2_K1Q_th_E4;
        TShape *Shape362;
        TLabel *DE2_K1Q_od_E4;
        TShape *Shape363;
        TLabel *DE2_K1Q_td_E4;
        TStaticText *StaticText41;
        TStaticText *StaticText43;
        TStaticText *StaticText44;
        TStaticText *StaticText45;
        TStaticText *StaticText46;
        TStaticText *StaticText47;
        TStaticText *Time_E4;
        TStaticText *StaticText49;
        TBitBtn *BitBtn11;
        TTabSheet *TabSheet7;
        TShape *Shape314;
        TLabel *Label105;
        TShape *Shape25;
        TLabel *TI_106_E5;
        TLabel *Label110;
        TLabel *Label111;
        TLabel *Label113;
        TLabel *Label118;
        TLabel *Label120;
        TLabel *Label122;
        TLabel *Label124;
        TShape *Shape322;
        TShape *Shape364;
        TShape *Shape365;
        TShape *Shape366;
        TShape *Shape367;
        TShape *Shape368;
        TShape *Shape369;
        TShape *Shape370;
        TShape *Shape371;
        TLabel *K1PC_04_E5;
        TShape *Shape372;
        TLabel *K1PI_01_E5;
        TShape *Shape373;
        TLabel *K1PC_02_E5;
        TShape *Shape374;
        TLabel *K1PI_03_E5;
        TShape *Shape375;
        TLabel *DE2_K1PC_04_E5;
        TShape *Shape376;
        TLabel *DE2_K1PI_01_E5;
        TShape *Shape377;
        TLabel *DE2_K1PC_02_E5;
        TShape *Shape378;
        TLabel *DE2_K1PI_03_E5;
        TLabel *Label139;
        TShape *Shape379;
        TShape *Shape380;
        TLabel *K1TI_01_E5;
        TShape *Shape381;
        TLabel *DE2_K1TI_01_E5;
        TShape *Shape382;
        TLabel *TI_105_E5;
        TStaticText *Time_E5;
        TStaticText *StaticText50;
        TLabel *Label107;
        TShape *Shape383;
        TShape *Shape384;
        TLabel *K1TI_02_E5;
        TShape *Shape385;
        TLabel *DE2_K1TI_02_E5;
        TLabel *Label126;
        TShape *Shape387;
        TShape *Shape388;
        TShape *Shape389;
        TShape *Shape390;
        TShape *Shape391;
        TLabel *PI_01_E5;
        TShape *Shape395;
        TShape *Shape397;
        TShape *Shape386;
        TLabel *Label129;
        TShape *Shape392;
        TShape *Shape393;
        TLabel *ZP_E5;
        TShape *Shape394;
        TLabel *DE2_ZP_E5;
        TShape *Shape396;
        TLabel *PE_01_E5;
        TImage *K1Fire_E5;
        TShape *Shape398;
        TImage *DE2_K1Fire_E5;
        TImage *DI_FIRE_E5;
        TStaticText *StaticText48;
        TShape *Shape399;
        TLabel *Label137;
        TLabel *L1_E5;
        TLabel *L2_E5;
        TLabel *L3_E5;
        TLabel *L4_E5;
        TLabel *L5_E5;
        TLabel *L6_E5;
        TLabel *L7_E5;
        TLabel *L8_E5;
        TLabel *L9_E5;
        TLabel *L10_E5;
        TLabel *L11_E5;
        TLabel *L12_E5;
        TLabel *L13_E5;
        TLabel *L14_E5;
        TLabel *L15_E5;
        TLabel *L16_E5;
        TShape *Shape400;
        TLabel *Label158;
        TLabel *K3Sost_gotov_E5;
        TLabel *K3Sost_vent_E5;
        TLabel *K3Sost_opress_E5;
        TLabel *K3Sost_gotovr_E5;
        TLabel *K3Sost_rozg_E5;
        TLabel *K3Sost_prog_E5;
        TLabel *K3Sost_avar_E5;
        TLabel *K3Sost_work_E5;
        TLabel *K3Sost_sign_E5;
        TShape *Shape401;
        TLabel *Label169;
        TLabel *DE2_K3Sost_gotov_E3;
        TLabel *DE2_K3Sost_vent_E5;
        TLabel *DE2_K3Sost_opress_E3;
        TLabel *DE2_K3Sost_gotovr_E5;
        TLabel *DE2_K3Sost_rozg_E5;
        TLabel *DE2_K3Sost_prog_E5;
        TLabel *DE2_K3Sost_avar_E5;
        TLabel *DE2_K3Sost_work_E5;
        TLabel *DE2_K3Sost_sign_E5;
        TStaticText *StaticText51;
        TStaticText *StaticText52;
        TStaticText *StaticText54;
        TLabel *Label179;
        TShape *Shape402;
        TShape *Shape403;
        TLabel *K1LI_01_E5;
        TShape *Shape404;
        TLabel *DE2_K1LI_01_E5;
        TCGauge *K1LI_01L_E5;
        TCGauge *DE2_K1LI_01L_E5;
        TLabel *EI_01_E5;
        TLabel *Label127;
        void __fastcall TrackBar1Change(TObject *Sender);
        void __fastcall BitBtn3Click(TObject *Sender);
        void __fastcall BitBtn4Click(TObject *Sender);
        void __fastcall BitBtn2Click(TObject *Sender);
        void __fastcall SpeedButton2Click(TObject *Sender);
        void __fastcall Timer1Timer(TObject *Sender);
        void __fastcall Timer2Timer(TObject *Sender);
        void __fastcall BBBuilderTrendClick(TObject *Sender);
        void __fastcall BBLastHourClick(TObject *Sender);
        void __fastcall BitBtn12Click(TObject *Sender);
        void __fastcall SpeedButton3Click(TObject *Sender);
        void __fastcall TBValueChange(TObject *Sender);
        void __fastcall TrendsMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall TrendsMouseMove(TObject *Sender, TShiftState Shift,
          int X, int Y);
        void __fastcall TrendsMouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall TrendsResize(TObject *Sender);
        void __fastcall TrendsGetAxisLabel(TChartAxis *Sender,
          TChartSeries *Series, int ValueIndex, AnsiString &LabelText);
        void __fastcall SBPlusClick(TObject *Sender);
        void __fastcall SBMinusClick(TObject *Sender);
        void __fastcall SBTagMinusClick(TObject *Sender);
        void __fastcall SBHourMinusClick(TObject *Sender);
        void __fastcall SBHourPlusClick(TObject *Sender);
        void __fastcall SBTagPlusClick(TObject *Sender);
        void __fastcall PageControl1Change(TObject *Sender);
        void __fastcall PageControl1DrawTab(TCustomTabControl *Control,
          int TabIndex, const TRect &Rect, bool Active);
        void __fastcall QListTrendAfterOpen(TDataSet *DataSet);
        void __fastcall LBListTrendsClick(TObject *Sender);
        void __fastcall Button4Click(TObject *Sender);
        void __fastcall QViewDataAfterScroll(TDataSet *DataSet);
        void __fastcall DBGridEh2DrawColumnCell(TObject *Sender,
          const TRect &Rect, int DataCol, TColumnEh *Column,
          TGridDrawState State);
        void __fastcall DBGridEh3DrawColumnCell(TObject *Sender,
          const TRect &Rect, int DataCol, TColumnEh *Column,
          TGridDrawState State);
        void __fastcall CLBFSClickCheck(TObject *Sender);
        void __fastcall DBGridEh4DrawColumnCell(TObject *Sender,
          const TRect &Rect, int DataCol, TColumnEh *Column,
          TGridDrawState State);
        void __fastcall DBGridEh4EditButtonClick(TObject *Sender);
        void __fastcall BitBtn6Click(TObject *Sender);
        void __fastcall BitBtn7Click(TObject *Sender);
        void __fastcall BitBtn8Click(TObject *Sender);
        void __fastcall BitBtn9Click(TObject *Sender);
        void __fastcall DBGridEh6DrawColumnCell(TObject *Sender,
          const TRect &Rect, int DataCol, TColumnEh *Column,
          TGridDrawState State);
        void __fastcall QConCheckTrendIDTagGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QConCheckTrendColorLineGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataIDTagGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataTDTGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataValGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataStatusGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataValProcGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QViewDataActiveGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QListSobIDTagGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QListSobValGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QListSobDlitGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QActiveSobIDTagGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall QActiveSobValGetText(TField *Sender,
          AnsiString &Text, bool DisplayText);
        void __fastcall N1pit_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N2pit_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N3pit_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N1pod_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N2pod_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N1set_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N2set_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N3set_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N10con_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N1pov_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N2pov_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N3pov_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N1gvs_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N2gvs_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N3gvs_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N4gvs_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall N11dre_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall Mode_ConN10_E2Click(TObject *Sender);
        void __fastcall Mode_DreN11_E2Click(TObject *Sender);
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
        void __fastcall Button3Click(TObject *Sender);
        void __fastcall Z3_C_E2Click(TObject *Sender);
        void __fastcall Label97Click(TObject *Sender);
        void __fastcall R1_PC204_Mode_E2Click(TObject *Sender);
        void __fastcall R2_PC206_Mode_E2Click(TObject *Sender);
        void __fastcall R3_PC207_Mode_E2Click(TObject *Sender);
        void __fastcall R4_PC212_Mode_E2Click(TObject *Sender);
        void __fastcall R5_PC213_Mode_E2Click(TObject *Sender);
        void __fastcall R7_LC404_Mode_E2Click(TObject *Sender);
        void __fastcall R6_LC403_Mode_E2Click(TObject *Sender);
        void __fastcall PT_201_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PT_202_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PT_203_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PC_204_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PT_205_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall LI_401_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall LI_402_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall LC_403_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall LC_404_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PC_206_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PC_207_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PT_210_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PT_211_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PC_212_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PC_213_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PV711_C_E2Click(TObject *Sender);
        void __fastcall PV741_C_E2Click(TObject *Sender);
        void __fastcall PV751_C_E2Click(TObject *Sender);
        void __fastcall PV761_C_E2Click(TObject *Sender);
        void __fastcall PV771_C_E2Click(TObject *Sender);
        void __fastcall PV721_C_E2Click(TObject *Sender);
        void __fastcall PV731_C_E2Click(TObject *Sender);
        void __fastcall Button5Click(TObject *Sender);
        void __fastcall BitBtn5Click(TObject *Sender);
        void __fastcall TNO_E2Click(TObject *Sender);
        void __fastcall TOB1_E2Click(TObject *Sender);
        void __fastcall TOB2_E2Click(TObject *Sender);
        void __fastcall TOB3_E2Click(TObject *Sender);
        void __fastcall BitBtn1Click(TObject *Sender);
        void __fastcall BitBtn10Click(TObject *Sender);
        void __fastcall K1ModeGaz_E3Click(TObject *Sender);
        void __fastcall K1PC_04_E3Click(TObject *Sender);
        void __fastcall K1ModeVoz_E3Click(TObject *Sender);
        void __fastcall K1PC_02_E3Click(TObject *Sender);
        void __fastcall K1PI_03_E3Click(TObject *Sender);
        void __fastcall K1ModeDym_E3Click(TObject *Sender);
        void __fastcall K1ModeVod_E3Click(TObject *Sender);
        void __fastcall K1LI_01_E3Click(TObject *Sender);
        void __fastcall DE2_K1ModeVod_E4Click(TObject *Sender);
        void __fastcall DE2_K1ModeDym_E4Click(TObject *Sender);
        void __fastcall DE2_K1LI_01_E4Click(TObject *Sender);
        void __fastcall BitBtn11Click(TObject *Sender);
        void __fastcall DE2_K1PC_04_E4Click(TObject *Sender);
        void __fastcall DE2_K1PI_03_E4Click(TObject *Sender);
        void __fastcall DE2_K1ModeGaz_E4Click(TObject *Sender);
        void __fastcall DE2_K1PC_02_E4Click(TObject *Sender);
        void __fastcall DE2_K1ModeVoz_E4Click(TObject *Sender);
        void __fastcall Npod_E2MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
private:	// User declarations
        unsigned long MasBits[4][1000]               ; // массив бит для отображения сложных элементов
        MyArhiv         *Arhiv                       ; // Архив для хранения информации (сохранение раз в секунду)
        unsigned int    ColorTrend[CountForTrends]   ; // Цвет серии на тренде
        TDateTime       DateArhiv                    ;
        AnsiString      FormatTrend[CountForTrends]  ; // Формат представления числа для трендов
        __int64         FreeKBytes                   ; // Количество требуемых свободных Кбайт для хранения архива
        int             IDTags_Trends[CountForTrends]; // ID тэгов для отображения на тренде
        unsigned int    Lic                          ; // количество тэгов в архиве
        double          Mashtab                      ; // Масштаб отображения трендов
        unsigned long   MigEkran                     ; // Счётчик для отображения мигания
        int             ModeApp                      ; // Режим приложения 0 - с автозапуском опроса и скрытием кнопок закрытия приложения, 1 - обычный режим
        bool            MoveVizir                    ; // Перемещение визира на тренде
        int             NewSizeWidth                 ; // Новая ширина экрана
        bool            NewSob                       ; // В архиве событий возникло новое событие
        AnsiString      Password                     ; // Пароль на изменение коэффициентов регуляторов и закрытия системы
        bool            PLUS_COUNT                   ; // увеличить счётчик для мигания
        double          Shkals_Min[CountForTrends]   ; // Шкала по минимуму в технологических единицах измерения для аналоговых сигналов
        double          Shkals_Max[CountForTrends]   ; // Шкала по максимуму в технологических единицах измерения для аналоговых сигналов
        double          Shkals_InMin[CountForTrends] ; // Шкала по минимуму в инженерных единицах измерения для аналоговых сигналов
        double          Shkals_InMax[CountForTrends] ; // Шкала по минимуму в инженерных единицах измерения для аналоговых сигналов
        bool            vismig                       ; // Отображение мигнаия

        void       __fastcall ChangeColor(TCanvas *Canvas,
                                         TDataSet *DataSet       ); // выбор цветов для отображения событий
        int        __fastcall GetCountSeries(int IDTrends, double *min_sh,   double *max_sh,
                                                           double *min_insh, double *max_insh,
                                                           int *id_tags,     unsigned int *ColorTrend,double *tmp_min, double *tmp_max
                                                                 ); // Определить количество серий
        int        __fastcall GetIDInfo(void)                     ; // Определить ID информации о тренде
        int        __fastcall GetIDFromString(AnsiString text)    ; // Определить ID элемента по строке
        AnsiString __fastcall GetIDTagCaption(TField *Sender)     ; // Определить информацию с описанием тэга по ID тэга (Архив событий)
        AnsiString __fastcall GetIDTagCaptionValue(TField *Sender); // Определить характеристики значения по ID тэга (Архив событий)
        int        __fastcall GetIDTrends(void)                   ; // Определить ID тренда
        AnsiString __fastcall GetNameEdIzm(int IDTag)             ; // Название единиц измерения по ID - тэга
        int        __fastcall RecNo(int IDTag)                    ; // По ID тэга определить номер записи
        void       __fastcall SetShagArhiv   (void)               ; // сетка архива - шаг
        void       __fastcall OnArhivSob(TMessage& Message)       ; // в архиве возникло новое предупредительное событие
        void       __fastcall PuskStopClick(TObject *Sender, int X, int Y, int IDPusk, int IDStop, AnsiString Text, bool AutoMode, int IDMode); // диалог Пуск/стоп насоса
        void       __fastcall OnOffRezerv(TObject *Sender, int X, int Y, AnsiString Text, AnsiString Text1, AnsiString Text2, AnsiString Text3,int ID_Rez1, int ID_Rez2, int ID_Rez3, int ID_WRez1, int ID_WRez2, int ID_WRez3); // диалог включения/выключения резерва (для насосов)
        void       __fastcall OpenCloseClick(TObject *Sender, int X, int Y, int IDPusk, int IDStop, int IDStopA, AnsiString Text, bool AutoMode, int IDMode); // диалог открытия/закрытия задвижки
        void       __fastcall RunRegul(int NumReg);
        void       __fastcall GetParamValue(System::TObject *Sender, int IDTag, double &ValParam, int &StatusParam);
        void       __fastcall RunInitShkals(AnsiString NameWindow, int ID_K4ma, int ID_K20ma, int X, int Y)        ;
        bool       __fastcall CheckPravInitShkals(void)           ; // проверка 
public:		// User declarations
        __fastcall TFMainForm(TComponent* Owner);
        BEGIN_MESSAGE_MAP
         MESSAGE_HANDLER(WM_USER+4,TMessage, OnArhivSob)      //  WM_USER+4 - в архиве на ПК возникло новое событие
        END_MESSAGE_MAP(TComponent)
};
//---------------------------------------------------------------------------
extern PACKAGE TFMainForm *FMainForm;
//---------------------------------------------------------------------------
#endif
